### ISSUE TITLE
How to determine if user is logged in?

### ISSUE THREAD

**Issue by daniel-cbw** [awurth/Slim#10]
Hello,

Thank you for providing this framework.

I was wondering how you would go about setting a condition for logged in status within Twig templating?

I see in container.php you are setting a global for auth, however that seems to return an object regardless.

If I needed to conditionally show content based on a user being logged in or not, how would I got about doing so?

**Comment by awurth** [comment]
Hi,

The `auth` variable in Twig templates is an instance of `Cartalyst\Sentinel\Sentinel` which has a `check()` method to check if a user is logged in, so you can call it from a Twig template like i did in [app/_navbar.twig](https://github.com/awurth/Slim/blob/689043718ecfac3a41930a922e7974cb89881c8a/templates/app/_navbar.twig#L4) to display the login/logout link:
``` twig
{% if auth.check() %}
```

**Comment by daniel-cbw** [comment]
Fantastic, thank you!
